version = 1

exclude_patterns = [
  "odoo/**",            # ignore Odoo base source code
  "addons/**",          # ignore all addons
  "!addons/hospital_management/**"  # but keep checking your module
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
