version = 1

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x"

[[transformers]]
name = "black"
enabled = true
exclude_patterns = [
  "venv/**",         # Ignore virtual environment
  "addons/**",       # Ignore addons folder
  "static/**", 
  "lib/**",
  "venvcd/**"      # (optional) ignore static files
]
